models:
  Random Forest:
    type: RandomForestRegressor
    params:
      n_estimators: [8, 16, 32, 64, 128, 256]

  Decision Tree:
    type: DecisionTreeRegressor
    params:
      criterion: ["squared_error", "friedman_mse", "absolute_error", "poisson"]

  Gradient Boosting:
    type: GradientBoostingRegressor
    params:
      learning_rate: [0.1, 0.01, 0.05, 0.001]
      subsample: [0.6, 0.7, 0.75, 0.8, 0.85, 0.9]
      n_estimators: [8, 16, 32, 64, 128, 256]

  Linear Regression:
    type: LinearRegression
    params: {}

  XGBRegressor:
    type: XGBRegressor
    params:
      learning_rate: [0.1, 0.01, 0.05, 0.001]
      n_estimators: [8, 16, 32, 64, 128, 256]
      max_depth: [3, 5, 7]
      subsample: [0.8, 1.0]
      colsample_bytree: [0.8, 1.0]

  CatBoosting Regressor:
    type: CatBoostRegressor
    params:
      depth: [6, 8, 10]
      learning_rate: [0.01, 0.05, 0.1]
      iterations: [30, 50, 100]
    verbose: False
    train_dir: artifacts/catboost_training

  AdaBoost Regressor:
    type: AdaBoostRegressor
    params:
      learning_rate: [0.1, 0.01, 0.5, 0.001]
      n_estimators: [8, 16, 32, 64, 128, 256]
